/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    solutions: Solution;
    'case-studies': CaseStudy;
    faq: Faq;
    industries: Industry;
    integrations: Integration;
    'blog-posts': BlogPost;
    leads: Lead;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    solutions: SolutionsSelect<false> | SolutionsSelect<true>;
    'case-studies': CaseStudiesSelect<false> | CaseStudiesSelect<true>;
    faq: FaqSelect<false> | FaqSelect<true>;
    industries: IndustriesSelect<false> | IndustriesSelect<true>;
    integrations: IntegrationsSelect<false> | IntegrationsSelect<true>;
    'blog-posts': BlogPostsSelect<false> | BlogPostsSelect<true>;
    leads: LeadsSelect<false> | LeadsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  roles?: ('admin' | 'editor')[] | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "solutions".
 */
export interface Solution {
  id: number;
  name: string;
  /**
   * URL-friendly identifier (e.g., "intelligent-agents")
   */
  slug: string;
  category: 'Core' | 'Operations' | 'Platform' | 'Governance';
  /**
   * Short description used on cards and as the SEO fallback (150–200 chars)
   */
  description: string;
  /**
   * One-line headline under the title on the detail page
   */
  heroTagline: string;
  /**
   * Card headline metric, e.g. "60%"
   */
  cardMetric: string;
  /**
   * Card metric label, e.g. "faster resolution"
   */
  cardMetricLabel: string;
  /**
   * Four short capability bullets shown on the solutions list card
   */
  features?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  problem: string;
  challenges?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  solutionOverview: string;
  capabilities?:
    | {
        title: string;
        description: string;
        /**
         * e.g., "94% accuracy" or "60% faster"
         */
        metric?: string | null;
        id?: string | null;
      }[]
    | null;
  howItWorks?:
    | {
        step: number;
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Systems this solution integrates with
   */
  integrations?:
    | {
        name: string;
        id?: string | null;
      }[]
    | null;
  results?:
    | {
        metric: string;
        label: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  faqs?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  cta: {
    headline: string;
    description: string;
  };
  /**
   * Optional path to a related case study, e.g. /case-studies/customer-service
   */
  caseStudyLink?: string | null;
  seo?: {
    /**
     * Page title for search engines (50–60 chars)
     */
    metaTitle?: string | null;
    /**
     * Page description for search engines (150–160 chars)
     */
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
    /**
     * Prevent this page from being indexed by search engines
     */
    noIndex?: boolean | null;
  };
  order?: number | null;
  /**
   * Feature this solution on the solutions list
   */
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies".
 */
export interface CaseStudy {
  id: number;
  title: string;
  /**
   * URL-friendly identifier (e.g., "document-processing")
   */
  slug: string;
  industry: string;
  /**
   * Detail-page subtitle, e.g. "for a Mid-Market Bank"
   */
  subtitle: string;
  card: {
    /**
     * Card title on the list page (may differ from the detail title)
     */
    title: string;
    /**
     * Shorter card subtitle, e.g. "Mid-Market Bank"
     */
    subtitle: string;
    /**
     * Metrics shown on the list card (value + label only)
     */
    metrics?:
      | {
          value: string;
          label: string;
          id?: string | null;
        }[]
      | null;
  };
  metrics?:
    | {
        value: string;
        label: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  challenge: {
    intro: string;
    painPoints?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  solution: {
    intro: string;
    components?:
      | {
          title: string;
          description: string;
          id?: string | null;
        }[]
      | null;
    timeline: string;
  };
  results?: {
    before?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    after?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  quote: {
    text: string;
    author: string;
  };
  seo?: {
    /**
     * Page title for search engines (50–60 chars)
     */
    metaTitle?: string | null;
    /**
     * Page description for search engines (150–160 chars)
     */
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
    /**
     * Prevent this page from being indexed by search engines
     */
    noIndex?: boolean | null;
  };
  order?: number | null;
  /**
   * Feature this case study on the list page
   */
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq".
 */
export interface Faq {
  id: number;
  question: string;
  answer: string;
  category?: ('agentic-ai' | 'saas-replacement' | 'service-process' | 'security-governance') | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "industries".
 */
export interface Industry {
  id: number;
  name: string;
  /**
   * URL-friendly identifier (e.g., "dealers-distributors")
   */
  slug: string;
  /**
   * Short headline metric, e.g. "80% Faster Order Entry"
   */
  tagline: string;
  /**
   * Emoji icon shown on cards and the detail hero, e.g. "📦"
   */
  icon: string;
  /**
   * Short description used on the industries list card (150–200 chars)
   */
  cardDescription: string;
  /**
   * Longer description shown under the title on the detail page hero
   */
  heroDescription: string;
  /**
   * Target audience description (e.g., "Utilities, energy producers, grid operators ($500M-$10B)")
   */
  targetAudience: string;
  /**
   * Market statistics and trends for this industry
   */
  marketContext?:
    | {
        /**
         * e.g., "65% of energy CEOs rank AI as top investment priority"
         */
        stat: string;
        /**
         * Source of the statistic
         */
        source?: string | null;
        id?: string | null;
      }[]
    | null;
  challenges?:
    | {
        challenge: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  aiSolutions?:
    | {
        title: string;
        description: string;
        /**
         * Key metric (e.g., "35% reduction in downtime")
         */
        metric?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Systems this industry commonly runs on
   */
  integrations?:
    | {
        name: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Industry-specific compliance standards
   */
  compliance?:
    | {
        /**
         * e.g., "HIPAA", "NERC CIP", "GxP"
         */
        standard: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  roiMetrics?:
    | {
        /**
         * e.g., "$50M distributor: $75K-$180K annual labor savings"
         */
        metric: string;
        id?: string | null;
      }[]
    | null;
  faqs?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Slugs of related solutions, e.g. "document-processing"
   */
  relatedSolutions?:
    | {
        slug: string;
        id?: string | null;
      }[]
    | null;
  seo?: {
    /**
     * Page title for search engines (50–60 chars)
     */
    metaTitle?: string | null;
    /**
     * Page description for search engines (150–160 chars)
     */
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
    /**
     * Prevent this page from being indexed by search engines
     */
    noIndex?: boolean | null;
  };
  order?: number | null;
  /**
   * Feature this industry on the industries list
   */
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "integrations".
 */
export interface Integration {
  id: number;
  name: string;
  category: 'sales-crm' | 'communication' | 'productivity' | 'support' | 'bi' | 'storage';
  logo: number | Media;
  url?: string | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts".
 */
export interface BlogPost {
  id: number;
  title: string;
  /**
   * URL-friendly identifier
   */
  slug: string;
  /**
   * Short summary for listings and SEO (150-200 chars)
   */
  excerpt: string;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  featuredImage?: (number | null) | Media;
  category: 'thought-leadership' | 'technical' | 'industry' | 'case-study' | 'how-to' | 'news';
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  relatedSolutions?: (number | Solution)[] | null;
  relatedIndustries?: (number | Industry)[] | null;
  /**
   * Add FAQs at the end of the post for AEO optimization
   */
  faqs?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  keyTakeaways?:
    | {
        takeaway: string;
        id?: string | null;
      }[]
    | null;
  status: 'draft' | 'published' | 'scheduled';
  /**
   * Publication date
   */
  publishedAt?: string | null;
  author?: string | null;
  seo?: {
    /**
     * Page title for search engines (50-60 chars)
     */
    metaTitle?: string | null;
    /**
     * Page description for search engines (150-160 chars)
     */
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
    noIndex?: boolean | null;
  };
  /**
   * Feature this post on the homepage/blog listing
   */
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: number;
  email: string;
  source?: ('cta-section' | 'footer' | 'hero') | null;
  /**
   * Path the lead was captured from
   */
  page?: string | null;
  consent?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'solutions';
        value: number | Solution;
      } | null)
    | ({
        relationTo: 'case-studies';
        value: number | CaseStudy;
      } | null)
    | ({
        relationTo: 'faq';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'industries';
        value: number | Industry;
      } | null)
    | ({
        relationTo: 'integrations';
        value: number | Integration;
      } | null)
    | ({
        relationTo: 'blog-posts';
        value: number | BlogPost;
      } | null)
    | ({
        relationTo: 'leads';
        value: number | Lead;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  roles?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "solutions_select".
 */
export interface SolutionsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  category?: T;
  description?: T;
  heroTagline?: T;
  cardMetric?: T;
  cardMetricLabel?: T;
  features?:
    | T
    | {
        text?: T;
        id?: T;
      };
  problem?: T;
  challenges?:
    | T
    | {
        text?: T;
        id?: T;
      };
  solutionOverview?: T;
  capabilities?:
    | T
    | {
        title?: T;
        description?: T;
        metric?: T;
        id?: T;
      };
  howItWorks?:
    | T
    | {
        step?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  integrations?:
    | T
    | {
        name?: T;
        id?: T;
      };
  results?:
    | T
    | {
        metric?: T;
        label?: T;
        description?: T;
        id?: T;
      };
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  cta?:
    | T
    | {
        headline?: T;
        description?: T;
      };
  caseStudyLink?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        noIndex?: T;
      };
  order?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies_select".
 */
export interface CaseStudiesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  industry?: T;
  subtitle?: T;
  card?:
    | T
    | {
        title?: T;
        subtitle?: T;
        metrics?:
          | T
          | {
              value?: T;
              label?: T;
              id?: T;
            };
      };
  metrics?:
    | T
    | {
        value?: T;
        label?: T;
        description?: T;
        id?: T;
      };
  challenge?:
    | T
    | {
        intro?: T;
        painPoints?:
          | T
          | {
              text?: T;
              id?: T;
            };
      };
  solution?:
    | T
    | {
        intro?: T;
        components?:
          | T
          | {
              title?: T;
              description?: T;
              id?: T;
            };
        timeline?: T;
      };
  results?:
    | T
    | {
        before?:
          | T
          | {
              text?: T;
              id?: T;
            };
        after?:
          | T
          | {
              text?: T;
              id?: T;
            };
      };
  quote?:
    | T
    | {
        text?: T;
        author?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        noIndex?: T;
      };
  order?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq_select".
 */
export interface FaqSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  category?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "industries_select".
 */
export interface IndustriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  tagline?: T;
  icon?: T;
  cardDescription?: T;
  heroDescription?: T;
  targetAudience?: T;
  marketContext?:
    | T
    | {
        stat?: T;
        source?: T;
        id?: T;
      };
  challenges?:
    | T
    | {
        challenge?: T;
        description?: T;
        id?: T;
      };
  aiSolutions?:
    | T
    | {
        title?: T;
        description?: T;
        metric?: T;
        id?: T;
      };
  integrations?:
    | T
    | {
        name?: T;
        id?: T;
      };
  compliance?:
    | T
    | {
        standard?: T;
        description?: T;
        id?: T;
      };
  roiMetrics?:
    | T
    | {
        metric?: T;
        id?: T;
      };
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  relatedSolutions?:
    | T
    | {
        slug?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        noIndex?: T;
      };
  order?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "integrations_select".
 */
export interface IntegrationsSelect<T extends boolean = true> {
  name?: T;
  category?: T;
  logo?: T;
  url?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts_select".
 */
export interface BlogPostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  content?: T;
  featuredImage?: T;
  category?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  relatedSolutions?: T;
  relatedIndustries?: T;
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  keyTakeaways?:
    | T
    | {
        takeaway?: T;
        id?: T;
      };
  status?: T;
  publishedAt?: T;
  author?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        noIndex?: T;
      };
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  email?: T;
  source?: T;
  page?: T;
  consent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  /**
   * Short brand line shown in the footer, under the logo.
   */
  brandTagline: string;
  /**
   * Fallback meta description for pages that do not set their own.
   */
  defaultSeoDescription: string;
  navItems?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  ctaButton: {
    label: string;
    href: string;
  };
  footerLinkGroups?:
    | {
        title: string;
        links?:
          | {
              label: string;
              href: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  socialLinks?:
    | {
        platform: 'x' | 'linkedin' | 'github' | 'youtube';
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  brandTagline?: T;
  defaultSeoDescription?: T;
  navItems?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  ctaButton?:
    | T
    | {
        label?: T;
        href?: T;
      };
  footerLinkGroups?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        id?: T;
      };
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}